name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.18] # Will add other versions as required
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: go test -race -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: go build -v ./...

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
