name: Go

on:
  push:
    branches:
  pull_request:
    branches:

jobs:

    test:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.18

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Test
          run: go test -race -v ./...

