name: Go

on:
  push:
    branches: 
  pull_request:
    branches:

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.18] # Will add other versions as required
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: go test -race -v ./...

